DFStudioWebMVC/Models/DialogArgs.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DFStudioWebMVC.Models
{
    public class DialogArgs
    {
        public string Title { get; set; }
        public string Message { get; set; }
    }
}

DFStudioWebMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DFStudioWebMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

DFStudioWebMVC/Controllers/LevelController.cs
using DFStudioData.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DFStudioWebMVC.Controllers
{
    public class LevelController : Controller
    {
        // GET: Level
        public ActionResult Index(int projectId)
        {
            var levels = Business.DFSDatabase.Context.Lev.Where(l => l.ProjectId == projectId);
            return View(levels);
        }

        public ActionResult Edit(int id)
        {
            var level = Business.DFSDatabase.Context.Lev.First(lev => lev.ID == id);
            return View(level);
        }

        public ActionResult NewLevel()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewLevel(Lev level)
        {
            //TODO: Create new level...

            return RedirectToAction("Index");
        }
    }
}

DFStudioWebMVC/Controllers/ProjectController.cs
using DFStudioData.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DFStudioWebMVC.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Project
        public ActionResult Index()
        {
            return View(Business.DFSDatabase.Context.Project.ToList());
        }

        public ActionResult Details(int id)
        {
            var project = Business.DFSDatabase.Context.Project.Where(p => p.ID == id);

            return RedirectToAction("Index"); //TODO: Update
        }

        public ActionResult NewProject()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewProject(Project proj)
        {
            //TODO: Create new project...

            return RedirectToAction("Index");
        }
    }
}

DFStudioWebMVC/Controllers/SectorsController.cs
using DFStudioData.Models;
using DFStudioWebMVC.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace DFStudioWebMVC.Controllers
{
    public class SectorsController : ApiController
    {
        ISectorRepository repo;

        public SectorsController(ISectorRepository sectorRepository)
        {
            repo = sectorRepository;
        }

        // GET: api/Sectors/5
        public Sector Get(int id)
        {
            return repo.GetById(id);
        }

        // GET: api/Sectors/ByLevelId/5
        [Route("api/Sectors/ByLevelId/{levelId}")]
        public IEnumerable<Sector> GetByLevelId(int levelId)
        {
            return repo.GetAllByLevId(levelId);
        }

        // POST: api/Sectors
        public void Post([FromBody]Sector value)
        {
            repo.Add(value);
        }

        // PUT: api/Sectors/5
        public void Put(int id, [FromBody]Sector value)
        {
            value.ID = id;

            //TODO: Make sure this works...
            repo.Update(value);
        }

        // DELETE: api/Sectors/5
        public void Delete(int id)
        {
            repo.Delete(repo.GetById(id));
        }
    }
}

DFStudioWebMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>

<p>This is a site for creating and editing Dark Forces Levels. Let me know what you think (@Html.ActionLink("Contact Me", "Contact"))</p>

DFStudioWebMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    10931 Waterpoint Dr<br />
    Allendale, MI 49401<br />
    <abbr title="Phone">P:</abbr>
    616.730.2239
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:mike.d.webb@gmail.com">mike.d.webb@gmail.com</a><br />
</address>

DFStudioWebMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "DF Studio Web Home";
}

<div class="jumbotron">
    <h1>Dark Forces Studio Web</h1>
    <p class="lead">Welcome to the website for Dark Forces Studio. Use the menu above for navigation.</p>
</div>

DFStudioWebMVC/Views/Level/Edit.cshtml
@model DFStudioData.Models.Lev

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div id="dfstudioweb">
    <canvas id="levCanvas" width="600" height="500" style="margin: 20px;"></canvas>
</div>

@section scripts {
@Scripts.Render("~/bundles/jquery-ui")
@Scripts.Render("~/bundles/backbone")
<script type="text/javascript" src="~/Scripts/levcanvas.js"></script>
<script type="text/javascript" src="~/Scripts/models/sector.js"></script>
<script type="text/javascript" src="~/Scripts/models/lev.js"></script>
<script type="text/javascript" src="~/Scripts/editMode-sector.js"></script>
<script type="text/javascript" src="~/Scripts/views/editView.js"></script>
<script type="text/javascript">
    $(function () {
        var view = new app.EditView();
        view.loadLevelGeometry(@Model.ID);
    });
</script>
}

DFStudioWebMVC/Views/Level/Index.cshtml
@model IEnumerable<DFStudioData.Models.Lev>

@{
    ViewBag.Title = "Project Levels";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "NewLevel")
</p>

@foreach (var item in Model) {
    Html.RenderPartial("LevelPartialView", item);
}

@Html.Partial(
    "DialogConfirmPartial",
    new DFStudioWebMVC.Models.DialogArgs {
        Title = "Delete Level",
        Message = "Sorry. Delete not implemented yet."
    }
)

DFStudioWebMVC/Views/Level/LevelPartialView.cshtml
@model DFStudioData.Models.Lev

<div class="raised">
    <h4>Level: @Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pallate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pallate)
        </dd>

    </dl>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id=Model.ID }, new { data_toggle = "modal", data_target = "#modalDialog" })
    </p>
</div>

DFStudioWebMVC/Views/Level/NewLevel.cshtml
@model DFStudioData.Models.Lev

@{
    ViewBag.Title = "NewLevel";
}

<h2>NewLevel</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lev</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pallate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pallate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pallate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DFStudioWebMVC/Views/Project/Index.cshtml
@model IEnumerable<DFStudioData.Models.Project>

@{
    ViewBag.Title = "Projects";
}

<h2>View</h2>

<p>
    @Html.ActionLink("Create New", "NewProject")
</p>

@foreach (var item in Model) {
    Html.RenderPartial("ProjectPartialView", item);
}

@Html.Partial(
    "DialogConfirmPartial",
    new DFStudioWebMVC.Models.DialogArgs {
        Title = "Delete Project",
        Message = "Sorry. Delete not implemented yet."
    }
)

DFStudioWebMVC/Views/Project/NewProject.cshtml
@model DFStudioData.Models.Project

@{
    ViewBag.Title = "NewProject";
}

<h2>NewProject</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DFStudioWebMVC/Views/Project/ProjectPartialView.cshtml
@model DFStudioData.Models.Project

<div class="raised">
    <h4>Project: @Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
        @Html.ActionLink("Levels", "Index", "Level", new { projectId=Model.ID }, null) |
        @Html.ActionLink("Delete", "Delete", new { id=Model.ID }, new { data_toggle = "modal", data_target = "#modalDialog" } )
    </p>
</div>

DFStudioWebMVC/Views/Shared/DialogConfirmPartial.cshtml
@model DFStudioWebMVC.Models.DialogArgs

<div id="modalDialog" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">@Model.Title</h4>
      </div>
      <div class="modal-body">
          <p>@Model.Message</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

DFStudioWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dark Forces Web Studio</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DF Web Studio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Projects", "Index", "Project")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dark Forces Web Studio</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>